// Code generated by protoc-gen-go.
// source: ProtobufUser.proto
// DO NOT EDIT!

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	ProtobufUser.proto

It has these top-level messages:
	ProtobufUser
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtobufUser_Phone_PhoneType int32

const (
	ProtobufUser_Phone_HOME  ProtobufUser_Phone_PhoneType = 0
	ProtobufUser_Phone_WORK  ProtobufUser_Phone_PhoneType = 1
	ProtobufUser_Phone_OTHER ProtobufUser_Phone_PhoneType = 2
)

var ProtobufUser_Phone_PhoneType_name = map[int32]string{
	0: "HOME",
	1: "WORK",
	2: "OTHER",
}
var ProtobufUser_Phone_PhoneType_value = map[string]int32{
	"HOME":  0,
	"WORK":  1,
	"OTHER": 2,
}

func (x ProtobufUser_Phone_PhoneType) String() string {
	return proto.EnumName(ProtobufUser_Phone_PhoneType_name, int32(x))
}
func (ProtobufUser_Phone_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

type ProtobufUser struct {
	Id     int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name   string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Phones []*ProtobufUser_Phone `protobuf:"bytes,3,rep,name=phones" json:"phones,omitempty"`
}

func (m *ProtobufUser) Reset()                    { *m = ProtobufUser{} }
func (m *ProtobufUser) String() string            { return proto.CompactTextString(m) }
func (*ProtobufUser) ProtoMessage()               {}
func (*ProtobufUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtobufUser) GetPhones() []*ProtobufUser_Phone {
	if m != nil {
		return m.Phones
	}
	return nil
}

type ProtobufUser_Phone struct {
	PhoneType   ProtobufUser_Phone_PhoneType `protobuf:"varint,1,opt,name=phoneType,enum=ProtobufUser_Phone_PhoneType" json:"phoneType,omitempty"`
	PhoneNumber string                       `protobuf:"bytes,2,opt,name=PhoneNumber,json=phoneNumber" json:"PhoneNumber,omitempty"`
}

func (m *ProtobufUser_Phone) Reset()                    { *m = ProtobufUser_Phone{} }
func (m *ProtobufUser_Phone) String() string            { return proto.CompactTextString(m) }
func (*ProtobufUser_Phone) ProtoMessage()               {}
func (*ProtobufUser_Phone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func init() {
	proto.RegisterType((*ProtobufUser)(nil), "ProtobufUser")
	proto.RegisterType((*ProtobufUser_Phone)(nil), "ProtobufUser.Phone")
	proto.RegisterEnum("ProtobufUser_Phone_PhoneType", ProtobufUser_Phone_PhoneType_name, ProtobufUser_Phone_PhoneType_value)
}

func init() { proto.RegisterFile("ProtobufUser.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x0a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0x0b, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x00, 0x71, 0x94, 0xbe, 0x30, 0x72,
	0xf1, 0x20, 0x0b, 0x0b, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06,
	0x01, 0x59, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x40, 0x11, 0xce, 0x20,
	0x30, 0x5b, 0x48, 0x9b, 0x8b, 0xad, 0x20, 0x23, 0x3f, 0x2f, 0xb5, 0x58, 0x82, 0x59, 0x81, 0x59,
	0x83, 0xdb, 0x48, 0x58, 0x0f, 0xc5, 0xe4, 0x00, 0x90, 0x5c, 0x10, 0x54, 0x89, 0xd4, 0x24, 0x46,
	0x2e, 0x56, 0xb0, 0x88, 0x90, 0x35, 0x17, 0x27, 0x58, 0x2c, 0xa4, 0xb2, 0x20, 0x15, 0x6c, 0x03,
	0x9f, 0x91, 0x2c, 0x16, 0x9d, 0x10, 0x12, 0xa4, 0x28, 0x08, 0xa1, 0x5e, 0x48, 0x81, 0x8b, 0x1b,
	0x2c, 0xee, 0x57, 0x9a, 0x9b, 0x94, 0x5a, 0x04, 0x75, 0x0e, 0x77, 0x01, 0x42, 0x48, 0x49, 0x8b,
	0x8b, 0x13, 0xae, 0x53, 0x88, 0x83, 0x8b, 0xc5, 0xc3, 0xdf, 0xd7, 0x55, 0x80, 0x01, 0xc4, 0x0a,
	0xf7, 0x0f, 0xf2, 0x16, 0x60, 0x14, 0xe2, 0xe4, 0x62, 0xf5, 0x0f, 0xf1, 0x70, 0x0d, 0x12, 0x60,
	0x72, 0x92, 0xe7, 0x12, 0x4f, 0xce, 0xcf, 0xd5, 0x2b, 0x4b, 0xcd, 0x2b, 0x2d, 0xce, 0x2f, 0x2d,
	0x4a, 0x4e, 0x85, 0x04, 0x07, 0xd0, 0x1d, 0x51, 0x2c, 0xa5, 0x40, 0x97, 0x24, 0xb1, 0x81, 0xf9,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x47, 0x40, 0xd1, 0x34, 0x01, 0x00, 0x00,
}
